### ISSUE TITLE
Consider adding MIP number to the filename of a MIP

### ISSUE THREAD

**Issue by t4top** [MinaProtocol/MIPs#15]
Currently, MIPs markdown files don't have their MIP numbers in their filenames. This make sorting difficult and will become harder to navigate as more MIPs are proposed. I suggest to have MIP numbers in the filenames just like Ethereum EIPs and Cardano CIPs repos.

A MIP filename can follow below naming convention: 

`mip-<number>-<feature-name>.md`

Where
\<number\> is the MIP number in a 4-digit format, left-padded with 0, and 
\<feature-name\> is hyphen-separated name of the title or major feature of the MIP.

For example,
`mip-0001-remove-supercharged-rewards.md` instead of `mip-remove-supercharged-rewards.md`, or
`mip-0004-zkapps.md` instead of `mip-zkapps.md`.

**Comment by kantp** [comment]
Resolved in #16.
